language: go
go:
  - 1.3
  - tip
before_install:
  - sudo add-apt-repository -y ppa:bpaquet/zeromq4-precise
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install -qq libzmq-dev libcap-dev; fi
